CITIES = [
    "London", "Birmingham", "Manchester", "Liverpool", "Leeds",
    "Sheffield", "Bristol", "Glasgow", "Edinburgh", "Cardiff", 
    "Belfast", "Leicester", "Nottingham", "Newcastle upon Tyne",
    "Sunderland", "Bradford", "Coventry", "Kingston upon Hull",
    "Stoke-on-Trent", "Wolverhampton", "Derby", "Southampton",
    "Portsmouth", "Plymouth", "Brighton and Hove", "Reading", "Milton Keynes",
    "Northampton", "Luton", "Swindon", "Oxford", "Cambridge",
    "York", "Bath", "Exeter", "Canterbury", "Norwich", "Peterborough",
    "Chelmsford", "Colchester", "Ipswich", "Salisbury", "Winchester", 
    "Worcester", "Gloucester", "Hereford", "Lincoln", "Wakefield",
    "Doncaster", "Rotherham", "Huddersfield", "Halifax", "Blackpool",
    "Preston", "Lancaster", "Carlisle", "Chester", "Warrington", "Bolton",
    "Oldham", "Rochdale", "Stockport", "Salford", "Burnley", "Blackburn",
    "Middlesbrough", "Darlington", "Hartlepool", "Durham", "Stirling",
    "Perth", "Dundee", "Aberdeen", "Inverness", "Paisley", "East Kilbride",
    "Ayr", "Dunfermline", "Kilmarnock", "Bangor", "Swansea", "Newport",
    "St Davids", "Wrexham", "Barry", "Caerphilly", "Merthyr Tydfil",
    "St Asaph", "Lisburn", "Derry", "Newry", "Armagh", "Carrickfergus",
    "Coleraine", "Omagh", "Enniskillen", "Londonderry", "Strabane"
]

STREETS = [
        "High Street", "Church Street", "Station Road", "Victoria Road", "London Road",
        "Park Road", "Mill Lane", "King Street", "Queen Street", "Market Street",
        "Main Street", "The Avenue", "Oak Road", "Oak Street", "Maple Avenue",
        "Cedar Road", "Willow Lane", "Ash Street", "Elm Road", "Pine Avenue",
        "Birch Lane", "Rose Street", "Victoria Street", "Albert Road", "Edward Street",
        "George Street", "Charles Road", "William Street", "Elizabeth Road",
        "Windsor Road", "Cambridge Road", "Oxford Street", "York Road", "Bristol Road",
        "Manchester Road", "Leeds Road", "Liverpool Road", "Birmingham Road", "Sheffield Road",
        "Newcastle Road", "Kingston Road", "Richmond Road", "Victoria Avenue", "Queen's Road",
        "Prince Street", "Castle Street", "Bridge Street", "Chapel Street", "School Lane",
        "Church Lane", "Garden Street", "Garden Road", "Park Avenue", "Park Lane",
        "Station Street", "Railway Road", "Mill Road", "Mill Street", "River Road",
        "Riverside Drive", "Meadow Lane", "Meadow Road", "Green Lane", "Green Street",
        "Springfield Road", "Spring Lane", "Summer Street", "Autumn Road", "Winter Lane",
        "Rosemary Road", "Lavender Avenue", "Hawthorn Road", "Holly Street", "Chestnut Road",
        "Sycamore Lane", "Willow Road", "Ash Grove", "Oak Grove", "Cedar Grove", "Beech Road",
        "Forest Road", "Woodland Drive", "Woodland Road", "Meadow View", "Hill View",
        "Park View", "Lake View", "Valley Road", "Hill Road", "North Road", "South Road",
        "East Road", "West Road", "Central Avenue", "Victoria Gardens", "Crown Street",
        "Market Road", "Regent Street", "Grove Road"
    ]