STORE_NAMES = ["Sunrise Market",
    "Sunset Market",
    "Morning Market",
    "Golden Basket",
    "Fresh Basket",
    "Daily Basket",
    "Market Basket",
    "Farm Basket",
    "Country Basket",
    "Local Basket",
    "Fresh Corner",
    "Daily Corner",
    "Market Corner",
    "Country Corner",
    "Village Corner",
    "The Pantry",
    "Market Pantry",
    "Country Pantry",
    "Harvest Pantry",
    "Fresh Pantry",
    "Daily Pantry",
    "The Grocer",
    "Village Grocer",
    "Country Grocer",
    "Local Grocer",
    "Family Grocer",
    "Corner Grocer",
    "Fresh Choice",
    "Daily Choice",
    "Local Choice",
    "Market Choice",
    "Country Choice",
    "Fresh Select",
    "Market Select",
    "Local Select",
    "Daily Select",
    "Prime Market",
    "Prime Grocer",
    "Prime Foods",
    "First Choice Foods",
    "Good Choice Market",
    "Better Basket",
    "Simply Fresh",
    "Simply Local",
    "Simply Market",
    "Everyday Foods",
    "Everyday Market",
    "Everyday Grocer",
    "Neighborhood Market",
    "Neighborhood Grocer",
    "Community Market",
    "Community Grocer",
    "Family Market",
    "Family Foods",
    "Family Pantry",
    "Village Foods",
    "Village Market",
    "Local Harvest",
]

STORE_SIZES = ["Small", "Medium", "Large"]