VENDOR_NAMES = [
    "Green Valley",
    "Golden Harvest",
    "Fresh Fields",
    "Meadow Brook",
    "Sunny Acres",
    "Oak Grove",
    "Riverdale",
    "Spring Hill",
    "Cedar Ridge",
    "Willow Creek",
    "Maple Grove",
    "Pine Valley",
    "Rosewood",
    "Hilltop",
    "Lakeside",
    "Woodland",
    "Harvest Moon",
    "Country Lane",
    "Green Meadow",
    "Silver Birch",
    "Golden Fields",
    "Fresh Meadow",
    "Apple Grove",
    "Cherry Hill",
    "Red Oak",
    "Blue River",
    "Sunny Brook",
    "Clearwater",
    "Highland",
    "Riverside",
    "Green Pastures",
    "Morning Star",
    "Golden Orchard",
    "Fresh Valley",
    "Meadow View",
    "Country Garden",
    "Spring Valley",
    "Oak Hill",
    "Cedar Valley",
    "Willow Ridge",
    "Maple Hill",
    "Pine Ridge",
    "Rose Valley",
    "Harvest Hill",
    "Green Ridge",
    "Silver Lake",
    "Golden Grove",
    "Fresh Acres",
    "Apple Valley",
    "Cherry Grove",
    "Red River",
    "Blue Meadow",
    "Sunny Fields",
    "Clear Spring",
    "Highland Valley",
    "River Grove",
    "Green Hills",
    "Morning Meadow",
    "Golden Ridge",
    "Fresh Brook",
    "Meadow Ridge",
    "Country Fields",
    "Spring Grove",
    "Oak Valley",
    "Cedar Hill",
    "Willow Valley",
    "Maple Ridge",
    "Pine Grove",
    "Rose Hill",
    "Harvest Valley",
    "Green Grove",
    "Silver Valley",
    "Golden Meadow",
    "Fresh Ridge",
    "Cherry Valley",
    "Red Hill",
    "Blue Ridge",
    "Sunny Grove",
    "Clear Valley",
    "Highland Grove",
    "River Valley",
    "Green Orchard",
    "Morning Valley",
    "Golden Brook",
    "Fresh Orchard",
    "Meadow Fields",
    "Country Grove",
    "Cedar Grove",
    "Willow Hill",
    "Maple Valley",
    "Pine Hill",
    "Rose Grove",
    "Harvest Grove",
    "Silver Ridge",
    "Amber Valley",
    "Autumn Grove",
    "Beechwood",
    "Bluebell Valley",
    "Brookfield",
    "Clover Hill",
    "Cotswold",
    "Country Brook",
    "Daisy Field",
    "Dawn Valley",
    "Elmwood",
    "Evergreen Valley",
    "Fairfield",
    "Fernwood",
    "Fox Hollow",
    "Green Acres",
    "Greenfield",
    "Hampton Valley",
    "Hawthorn Grove",
    "Hazelwood",
    "Heather Hill",
    "Hillside",
    "Honeybrook",
    "Ivory Fields",
    "Kingswood",
    "Lavender Hill",
    "Little Meadow",
    "Longfield",
    "Meadowbrook",
    "Moorland",
    "Oakwood",
    "Orchard Hill",
    "Pheasant Valley",
    "Primrose Fields",
    "Redwood",
    "Rosebank",
    "Rosefield",
    "Silverbrook",
    "Springfield",
    "Stonebridge",
    "Stonefield",
    "Sunnydale",
    "Sunrise Valley",
    "Thornfield",
    "Valley Brook",
    "Westfield",
    "White Oak",
    "Wildflower",
    "Woodbridge",
    "Woodland Valley",
    "Applebrook",
    "Applewood",
    "Ashbourne",
    "Ashwood",
    "Autumn Fields",
    "Briarwood",
    "Brookside",
    "Buttercup Valley",
    "Cloverfield",
    "Dovecote",
    "Eagle Hill",
    "Fairview",
    "Fern Valley",
    "Foxfield",
    "Greenbrook",
    "Greenhill",
    "Harvest Brook",
    "Hazel Grove",
    "Heatherfield",
    "Hollybrook",
    "Kingsley",
    "Meadowfield",
    "Oakbrook",
    "Orchard Valley",
    "Pinewood",
    "Primrose Valley",
    "Redbrook",
    "Rosewood Valley",
    "Silverfield",
    "Springbrook",
    "Stonehill",
    "Sunnybrook",
    "Thornwood",
    "Valleyfield",
    "Westbrook",
    "Whitefield",
    "Wildwood",
    "Willowfield",
    "Woodcroft",
    "Brookvale",
    "Cedarbrook",
    "Clearfield",
    "Evergreen Fields",
    "Goldenfield",
    "Hillside Valley",
    "Meadowvale"
]

VENDOR_MODIFIERS = [
    "Farms",
    "Farm",
    "Produce",
    "Fresh Produce",
    "Foods",
    "Food Co.",
    "Grocers",
    "Growers",
    "Orchards",
    "Market",
    "Suppliers",
    "Wholesale",
    "Organics",
    "Organic Foods",
    "Fresh Foods",
    "Provisions",
    "Harvest",
    "Agriculture",
    "Dairy",
    "Meats",
    "Farmhouse",
    "Farmstead",
    "Grocery",
    "Orchard",
    "Markets",
    "Supply Co.",
    "Wholesalers",
    "Organic Produce",
    "Naturals",
    "Natural Foods",
    "Food Group",
    "Food Supply",
    "Harvest Co.",
    "Fresh Market",
    "Fresh Goods",
    "Farm Goods",
    "Farm Produce",
    "Country Foods",
    "Country Produce",
    "Dairy Co.",
    "Meat Co.",
    "Butchers",
    "Bakery",
    "Bakers",
    "Fruit & Veg",
    "Fruit Growers",
    "Vegetable Growers",
    "Fine Foods",
    "Fine Produce",
    "Food Traders",
    "Food Merchants",
    "Producers",
    "Distributors"
]
